spring.application.name=ticket-service
server.port=8082

spring.cloud.config.enabled=false

#eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:mysql://localhost:3306/nr_ticket_db
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/nr_ticket_db
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.datasource.hikari.maximum-pool-size=2